Feat/checkout
Deltinha/back-phone-store pull request #13
Opened 2021-11-14 11:15 UTC by Deltinha

Devo ter cobrido todas as validações necessárias e todos os testes.
A estrutura que você montou ficou muito boa pra programar. Acho que consegui manter tudo no seu devido lugar.

2021-11-14 21:45 UTC, rabbithay requested changes
muito bom!! a cobertura de validações e testes ficou bem completa e a lógica ta bem semântica. o unico caso teste que não vi é o retorno de erro 402

de performance, o que pode ser um problema é aquela requisição dentro de um loop. comentei lá como sugestão montar a query no loop e fazer a reuqisição fora. não sei se seria a melhor forma de fazer isso ainda, mas podemos pensar juntos.

2021-11-14 21:45 UTC, rabbithay commented on src/repositories/checkout.js
> +  }
esse value que vc está adicionando ta sendo o do produto mesmo ou da compra? acho que o do produto ta dentro do item, assim como o id do produto e a quantidade

2021-11-14 21:45 UTC, rabbithay commented on src/repositories/checkout.js
> +  }
essas requisições pro branco dentro de um laço de repetição podem deixar o sistema muito lento. acho que seria melhor usar o loop para montar a estrutura da query, e enviar para o banco depois, com apenas uma requisição

2021-11-14 21:45 UTC, rabbithay commented on src/services/checkout.js
> +  });
como esses dois `forEach`percorrem a mesma array, poderiam ser um só

2021-11-14 22:47 UTC, Deltinha commented on src/repositories/checkout.js
> +  }
Sobre o value, é o value do produto. O back só deve receber o id do produto e a quantidade. Através dessas informações ele consegue buscar no banco o valor. Imaginei que não seria legal receber o valor na requisição. Já pensou se alguém manda uma compra de valor 0 na maldade?
Eu até me toquei nesse detalhe de montar a query separadamente. Mas não tinha conseguido pensar em uma forma.

2021-11-15 00:51 UTC, Deltinha commented
O 402 foi um erro meu. Acho que o dedo escorregou ou algo do tipo.

2021-11-15 02:06 UTC, Deltinha commented
Tudo corigido.

2021-11-15 02:59 UTC, rabbithay approved these changes
a solução da query ficou muito boa!!! tudo lindo :rocket:

2021-11-15 03:00 UTC, merged